[package]
name = "curvetest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = { version = "4.0.0-rc.0" }
rust_sodium = "0.10.2"
rand = "0.8.5"
